const gulp     = require('gulp');
const config   = require('../../config').iconFonts;
const swig     = require('gulp-swig');
const rename   = require('gulp-rename');

module.exports = function(codepoints, options) {
  gulp.src(config.template)
    .pipe(swig({
      data: {
        icons: codepoints.map(function(icon) {
          return {
            name: icon.name,
            code: icon.codepoint.toString(16)
          }
        }),

        fontName: config.options.fontName,
        fontPath: config.fontPath,
        className: config.className,
        comment: 'DO NOT EDIT DIRECTLY! Generated by gulp/tasks/iconFont.js from ' + config.template
      }
    }))
    .pipe(rename(config.scssOutputName))
    .pipe(gulp.dest(config.scssDest));
};
